//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Amz
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOrderItem
    {
        public int Id { get; set; }
        public Nullable<int> O_id { get; set; }
        public Nullable<int> P_id { get; set; }
        public Nullable<decimal> U_price { get; set; }
        public int Quantity { get; set; }
        public string P_name { get; set; }
    
        public virtual APrduct APrduct { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
