//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Amz
{
    using System;
    using System.Collections.Generic;
    
    public partial class APrduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APrduct()
        {
            this.AOrderItem = new HashSet<AOrderItem>();
        }
    
        public int Id { get; set; }
        public string P_Name { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> D_type { get; set; }
    
        public virtual ADtype ADtype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AOrderItem> AOrderItem { get; set; }
        public virtual AType AType { get; set; }
    }
}
