//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Amz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APD65_63011212052Entities1 : DbContext
    {
        public APD65_63011212052Entities1()
            : base("name=APD65_63011212052Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADtype> ADtype { get; set; }
        public virtual DbSet<AOrderItem> AOrderItem { get; set; }
        public virtual DbSet<APrduct> APrduct { get; set; }
        public virtual DbSet<AType> AType { get; set; }
        public virtual DbSet<OrderProduct> OrderProduct { get; set; }
    }
}
