//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab0501_Simple_Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int register_id { get; set; }
        public string student_id { get; set; }
        public string subject_id { get; set; }
    }
}
